# Classes de Conjuntos {#cap1}

Neste capítulo estudaremos certas classes de conjuntos sobre as quais, nos capítulos seguintes, definiremos diversos tipos de funções. Entre esses tipos têm destaque muito especial as medidas finitamente aditivas e $\sigma$-aditivas positivas e com sinal, que estudaremos posteriormente. As Props. 1.6 e 1.7 são as mais importantes. Os Exemplos 1.1 e 1.2 devem ser bem analisados e lembrados juntamente com as diversas classes de conjuntos gerados por eles.

**DEFINIÇÃO 1.1.** $\mathbb{S}$ é um semi-anel se, e somente se,

$$\text{i) } A, B \in \mathbb{S} \Rightarrow A \cap B \in \mathbb{S};$$

$\text{ii) } A, B \in \mathbb{S} \Rightarrow A-B = \sum\limits_{i=1}^{n} C_i$, para algum $n \in \mathbb{N}$ e para alguns $C_i \in \mathbb{S}, 1 \le i \le n$ (O sinal $\sum$ indica união disjunta). Decorre de ii) que $\varnothing \in \mathbb{S}$.

**EXEMPLO 1.1.** $\Omega = \mathbb{R}^1$ $$\mathbb{S} = \{(a, b]: a, b \in \mathbb{R}^1, a \le b\}.$$

**EXEMPLO 1.2.** $\Omega = \mathbb{R}^n$ $$\mathbb{S} = \{(a_1, b_1] \times \dots \times (a_n, b_n]: a_i, b_i \in \mathbb{R}^1, a_i \le b_i, 1 \le i \le n\}.$$

**EXEMPLO 1.3.** $\Omega$ qualquer; $$\mathbb{S} = \{A \subseteq \Omega: A \text{ é unitário ou vazio}\}.$$

**EXEMPLO 1.4.** $\Omega = \mathbb{R}^1$, $$\mathbb{S} = \{(a, b], (a, b), [a, b), [a, b], a \in \mathbb{R}^1, b \in \mathbb{R}, a \le b\}.$$

**DEFINIÇÃO 1.2.** $\mathbb{S}$ é semi-álgebra se é semi-anel e $\Omega \in \mathbb{S}$.

**Observação 1.** $$\mathbb{S} \text{ é semi-álgebra se, e somente se,}$$

i)  $\Omega \in \mathbb{S}$;

ii) $A, B \in \mathbb{S} \Rightarrow A \cap B \in \mathbb{S}$;

iii) $A \in \mathbb{S} \Rightarrow A^c = \sum\limits_{i=1}^{n} C_i, \ C_i \in \mathbb{S}$ ($A^c$ é o complementar de $A$ em relação a $\Omega$).

Seja agora $\mathbb{R}$ uma classe de conjuntos tal que $\varnothing \notin \mathbb{R} \subseteq \mathbb{P}(\Omega)$.

**PROPOSIÇÃO 1.1. São equivalentes as seguintes afirmações:** $$\mathbb{R} \text{ é fechada com relação a:}$$

i)  união finita e diferença;

ii) união finita e diferença própria;

iii) diferença simétrica e interseção finita;

iv) união finita disjunta, diferença própria e interseção finita.

**Demonstração.** Decorre de identidades elementares da teoria dos conjuntos. Veja o Exerc. 2.

**DEFINIÇÃO 1.3.** $\mathbb{R}$ é anel se satisfaz alguma das condições da Prop. 1.1 (e conseqüentemente às quatro condições). $\mathbb{R}$ é álgebra se é anel e $\Omega \in \mathbb{R}$.

**Observação 2.** $\mathbb{R}$ é álgebra se, e somente se, é fechada com relação à união finita e complementação.

**Observação 3.** A interseção de uma família qualquer de anéis é um anel. Portanto, dada uma classe não-vazia $\mathscr{C}$ de subconjuntos de $\Omega$, podemos definir o anel gerado por $\mathscr{C}$, como o menor anel que contém $\mathscr{C}$, que, como é claro, coincide com a interseção de todos os anéis que contém $\mathscr{C}$.

**Observação 4.** Análoga à observação 3 com álgebra no lugar do anel.

**PROPOSIÇÃO 1.2.** Se $\mathbb{S}$ é um semi-anel (resp. semi-álgebra), então a família $\mathbb{R}(\mathbb{S})$ das somas finitas disjuntas de elementos de $\mathbb{S}$ é um anel (resp. álgebra) e coincide com o anel (resp. álgebra) gerado por $\mathbb{S}$.

**Demonstração** Provaremos apenas para anel, pois para álgebra o raciocínio é idêntico.

Vamos ver que $\mathbb{R}(\mathbb{S})$ é um anel, o que prova uma das inclusões. A outra é imediata.

Vamos usar a Prop. 1.1 (iv).

Por definição, $\mathbb{R}(\mathbb{S})$ é fechado por união finita disjunta.

Que $\mathbb{R}(\mathbb{S})$ é fechado em relação à interseção finita segue da identidade $$ \left(\sum_{i=1}^{n} C_i\right) \cap \left(\sum_{j=1}^{m} B_j\right) = \sum_{i=1}^{n} \sum_{j=1}^{m} (C_i \cap B_j), $$ e do fato de que $\mathbb{S}$ é fechado por interseção finita.

Vamos mostrar agora que $\mathbb{R}(\mathbb{S})$ é fechado por diferença própria.

Sejam $\sum\limits_{i=1}^{n} C_i$, $\sum\limits_{j=1}^{m} B_j$ com $C_i, B_j \in \mathbb{S}$ tais que: $$ \sum_{j=1}^{m} B_j \subseteq \sum_{i=1}^{n} C_i. $$ $$ \begin{aligned} \sum_{i=1}^{n} C_i - \sum_{j=1}^{m} B_j &= \sum_{i=1}^{n} \left(C_i - \sum_{j=1}^{m} B_j\right) = \sum_{i=1}^{n} \left(C_i - \sum_{j=1}^{m} (B_j \cap C_i)\right) = \\ &= \sum_{i=1}^{n} \left(C_i - \bigcup_{j=1}^{m} (B_j \cap C_i)\right). \end{aligned} $$

Como $B_j \cap C_i \in \mathbb{S}$, $C_i - (B_j \cap C_i)$ é uma soma finita de elementos de $\mathbb{S}$, ou seja, um elemento de $\mathbb{R}(\mathbb{S})$. Agora basta usar o fato de que $\mathbb{R}(\mathbb{S})$ é fechado em relação à soma finita.

Seja agora $\mathscr{A}$ tal que $\varnothing \neq \mathscr{A} \subseteq \mathbb{P}(\Omega)$.

**DEFINIÇÃO 1.4.** $\mathscr{A}$ é $\sigma$-anel se, e somente se, é fechada por diferença e por união enumerável. Se $\mathscr{A}$ é $\sigma$-anel e $\Omega \in \mathscr{A}$, $\mathscr{A}$ é dita $\sigma$-álgebra.

**PROPOSIÇÃO 1.3.** $\mathscr{A}$ é $\sigma$-anel se, e somente se, é fechado por interseção finita, diferença própria e soma enumerável. (Isto é, união enumerável disjunta).

**Demonstração** Suponhamos que $\mathscr{A}$ seja $\sigma$-anel. Como $\mathscr{A} \neq \varnothing$, e é fechado por diferença, $\varnothing = A - A \in \mathscr{A}$, para $A \in \mathscr{A}$. Então $\mathscr{A}$ é fechado por união finita, pois toda união finita é igual a uma união enumerável, onde todos os conjuntos, menos um número finito, são o vazio. Então $\mathscr{A}$ é anel, e portanto fechado por interseção finita. Além disso $\mathscr{A}$ é fechado por soma enumerável pela definição de $\sigma$-anel. Suponhamos agora que $\mathscr{A}$ seja fechado por interseção finita, diferença própria e soma enumerável. Exatamente como na 1.$^{\text{a}}$ parte prova-se que $\varnothing \in \mathscr{A}$, e como ele é fechado por soma enumerável, é fechado por soma finita. Então $\mathscr{A}$ é anel. Agora para provar que $\mathscr{A}$ é fechado por união enumerável basta usar a identidade: $$ \bigcup_{i=1}^{\infty} A_i = A_1 + \sum_{i=2}^{\infty} \left(A_i - \bigcup_{j=1}^{i-1} A_j\right). $$

**PROPOSIÇÃO 1.4.** Todo $\sigma$-anel é fechado por interseção enumerável.

**Demonstração** Basta ver que $\bigcap\limits_{i=1}^{\infty} A_i = A_1 - \bigcup\limits_{i=1}^{\infty} (A_1 - A_i).$

**Observação 5.** Decorre da definição e da proposição anterior que todo $\sigma$-anel é fechado em relação ao lim sup e lim inf.

**PROPOSIÇÃO 1.5.** $\mathscr{A}$ é $\sigma$-álgebra se, e somente se, é fechada por uniões enumeráveis e complementos.

**Demonstração** Veja Exerc. 3. (Lembre-se que $\mathscr{A} \neq \varnothing$).

**Observação 6.** A interseção de uma família qualquer de $\sigma$-anéis ($\sigma$-álgebras) e um $\sigma$-anel ($\sigma$-álgebra). Portanto, dada uma classe não-vazia $\mathscr{C}$ de subconjuntos de $\Omega$, podemos definir o $\sigma$-anel ($\sigma$-álgebra) gerado por $\mathscr{C}$ como o menor $\sigma$-anel ($\sigma$-álgebra) que contém $\mathscr{C}$, e que, como é claro, coincide com a interseção de todos os $\sigma$-anéis ($\sigma$-álgebras) que contém $\mathscr{C}$.

*Notação.* Adotaremos o símbolo $\sigma(\mathscr{C})$ ($\tilde{\sigma}(\mathscr{C})$) para denotar a $\sigma$-álgebra ($\sigma$-anel) gerada pela família de conjuntos $\mathscr{C}$.

**DEFINIÇÃO 1.5.** $\mathscr{A}$ é uma classe $\sigma$-aditiva se, e somente se, $\Omega \in \mathscr{A}$, e é fechada por diferença própria, soma finita, e união crescente (i. e., $A_1 \subseteq A_2 \subseteq \dots, A_i \in \mathscr{A}, \forall i$, implica $\bigcup\limits_{i=1}^{\infty} A_i \in \mathscr{A}$).

**Observação 7.** Análoga à Obs. 6 com classe $\sigma$-aditiva em lugar de $\sigma$-anel.

**PROPOSIÇÃO 1.6.** Se $\mathscr{C}$ é uma classe não-vazia de conjuntos, fechada por interseção finita, então a classe $\sigma$-aditiva gerada por $\mathscr{C}$ é igual a $\sigma(\mathscr{C})$.

**Demonstração** Seja $\mathbb{F}$ a classe $\sigma$-aditiva gerada por $\mathscr{C}$. Como $\sigma(\mathscr{C})$ é uma classe $\sigma$-aditiva, o que é fácil de verificar, $\mathbb{F} \subseteq \sigma(\mathscr{C})$. De modo análogo, se provarmos que $\mathbb{F}$ é $\sigma$-álgebra, teremos $\sigma(\mathscr{C}) \subseteq \mathbb{F}$, terminando a prova.

Observémos inicialmente que toda classe $\sigma$-aditiva fechada por interseção finita, é uma $\sigma$-álgebra pela Prop. 1.3: para provar isso basta usar o fato de que $$ \sum\limits_{i=1}^{\infty} A_i = \bigcup\limits_{i=1}^{\infty} \sum\limits_{n=1}^{i} A_n \text{ (note que no membro direito temos uma união crescente)}. $$

Portanto, basta provar que $\mathbb{F}$ é fechada por interseção finita.

Seja $\mathbb{H} = \{A \subseteq \Omega; \forall B \in \mathbb{F}, A \cap B \in \mathbb{F}\}$. É suficiente provar que $\mathbb{F} \subseteq \mathbb{H}$. Ao mostrarmos, porém, que $\mathbb{H}$ é uma classe $\sigma$-aditiva e $\mathscr{C} \subseteq \mathbb{H}$, $\mathbb{F} \subseteq \mathbb{H}$ estará provada. Usando as identidades: $$ (A_1 - A_2) \cap B = (A_1 \cap B) - (A_2 \cap B), $$ $$ (A_1 + A_2) \cap B = (A_1 \cap B) + (A_2 \cap B), $$ $$ (\bigcup\limits_{i=1}^{\infty} A_i) \cap B = \bigcup\limits_{i=1}^{\infty} (A_i \cap B) $$ vemos que $\mathbb{H}$ é classe $\sigma$-aditiva.

Para mostrar que $\mathbb{H} \supseteq \mathscr{C}$, seja $C \in \mathscr{C}$ e constrói-se a coleção: $$ \mathbb{D} = \{A \subseteq \Omega: A \cap C \in \mathbb{F}\}. $$

É suficiente provar que $\mathbb{F} \subseteq \mathbb{D}$ para obtermos $C \in \mathbb{H}$. Novamente isso se reduz a mostrar que $\mathbb{D}$ é uma classe $\sigma$-aditiva (modo análogo ao que usamos para $\mathbb{H}$) e que $\mathbb{D} \supseteq \mathscr{C}$. Este último fato decorre da hipótese de $\mathscr{C}$ ser fechada por interseção finita.

**DEFINIÇÃO 1.7.** $\mathscr{A}$ é uma classe monotônica se é fechada por união enumerável crescente e por interseção enumerável decrescente.

**Observação 8.** Análoga à observação 6 com classe monotônica em lugar de $\sigma$-anel.

**PROPOSIÇÃO 1.7.** Se $\mathbb{R}$ é uma álgebra (anel), então a classe monotônica gerada por $\mathbb{R}$ é $\sigma(\mathbb{R}) \ (\tilde{\sigma}(\mathbb{R}))$.

**Demonstração** A demonstração dessa proposição é análoga à da proposição anterior. (Veja Halmos [1], p. 27, Teor. B). (Veja o Exerc. 4).

## Exercícios {.unnumbered}

1.  $\{\Omega_i\}_{i \in I}$ uma família de conjuntos e $\mathbb{S}_i$ uma semi-álgebra sobre $\Omega_i$. Seja $\Omega = \prod\limits_{i \in I} \Omega_i$ e $\mathbb{S} = \{\prod\limits_{i \in I} B_i \text{ onde } B_i = \Omega_i \text{ para todos os índices, salvo um número finito nos quais } B_i \in \mathbb{S}_i \}$. Então $\mathbb{S}$ é uma semi-álgebra sobre $\Omega$ (Essa semi-álgebra é chamada semi-álgebra produto).
2.  Demonstrar a Prop. [1.1.](#cap1)
3.  Demonstrar a Prop. [1.5.](#cap1)
4.  Demonstrar a Prop. [1.7.](#cap1)
5.  Calcular $\sigma(\mathbb{S})$ e $\overline{\sigma}(\mathbb{S})$ onde $\mathbb{S}$ é o semi-anel descrito no Exemplo [1.3.](#cap1)
6.  Seja $\mathscr{C}$ uma classe de conjuntos tal que $\varnothing \in \mathscr{C}$. Seja $\tilde{\mathscr{C}}$ a classe dos conjuntos que são uniões finitas de diferenças de elementos de $\mathscr{C}$. Definimos $\mathscr{C}_0 = \mathscr{C}$ e para $n \ge 1$, $\mathscr{C}_n = \tilde{\mathscr{C}}_{n-1}$. Provar:

<!-- -->

a)  $\mathbb{R}(\mathscr{C}) = \bigcup\limits_{n=0}^{\infty} \mathscr{C}_n$.

b)  se $\mathscr{C}$ é enumerável, $\mathbb{R}(\mathscr{C})$ também o é.

<!-- -->

7.  Se $(X, \tau)$ é um espaço topológico, denotaremos com $\mathscr{B}(X, \tau)$ ou $\mathscr{B}(\tau)$ simplesmente a $\sigma$-álgebra gerada pela topologia. Essa $\sigma$-álgebra é chamada $\sigma$-álgebra de Borel. Provar que a $\sigma$-álgebra de Borel de $\mathbb{R}^n$ coincide com a $\sigma$-álgebra gerada pelos conjuntos descritos no Exemplo [1.2.](#cap1)
8.  Seja $\mathscr{C}$ uma classe de conjuntos não-vazia. Seja $A \in \sigma(\mathscr{C})$. Então existe uma classe enumerável $\mathscr{D} \subseteq \mathscr{C}$, tal que $A \in \sigma(\mathscr{D})$.
9.  Seja $\mathscr{C}$ uma classe não-vazia de conjuntos, e $A \subseteq \Omega$. Denotamos com $\mathscr{C} \cap A = \{C \cap A: C \in \mathscr{C}\}$. Provar que $\sigma(\mathscr{C} \cap A) = \sigma(\mathscr{C}) \cap A$ onde $\sigma(\mathscr{C} \cap A)$ indica a $\sigma$-álgebra gerada em $A$ por $\mathscr{C} \cap A$. O resultado continua válido se $\sigma$ for trocado por $\overline{\sigma}$.
10. Uma $\sigma$-álgebra $\mathscr{A}$ é chamada separável, se $\exists \mathscr{A}_0 \subseteq \mathscr{A}, \mathscr{A}_0$ enumerável, e tal que $\sigma(\mathscr{A}_0) = \mathscr{A}$.

<!-- -->

a)  provar que a $\sigma$-álgebra de Borel de $\mathbb{R}^n$ é separável;
b)  provar que a $\sigma$-álgebra de Borel de um espaço métrico separável é separável;
c)  provar que a $\sigma$-álgebra de Borel de um espaço topológico com base enumerável é separável e
d)  dar um exemplo de uma $\sigma$-álgebra $\mathscr{A}$ separável, e uma sub-$\sigma$-álgebra $\mathscr{B} \subseteq \mathscr{A}$, tal que $\mathscr{B}$ não é separável.

<!-- -->

11. Dado um conjunto $\Omega$ e uma $\sigma$-álgebra $\mathscr{A}$ em $\Omega$, chamaremos espaço mensurável ao par $(\Omega, \mathscr{A})$. Seja $(\Omega, \mathscr{A})$ um espaço mensurável; $\mathscr{B} \subseteq \mathscr{A}$ uma álgebra enumerável, tal que $\sigma(\mathscr{B}) = \mathscr{A}$. Para $\omega \in \Omega$; $$ A(\omega) = \cap \{A: A \in \mathscr{A}, \omega \in A\}. $$ Provar que $A(\omega) = \cap \{B: B \in \mathscr{B}, \omega \in B\}$. Em particular $A(\omega) \in \mathscr{A}$.
12. Seja $\Omega = \mathbb{R}^2$ e $R(y) = \{(x, y): x \in \mathbb{R}^1\}$ (reta horizontal). Seja $\mathscr{C} = \{R(y): y \in \mathbb{R}^1\}$. Calcular:

<!-- -->

a)  $\sigma$-anel gerado por $\mathscr{C}$;
b)  $\sigma$-álgebra gerada por $\mathscr{C}$ e
c)  a classe monotônica gerada por $\mathscr{C}$.

<!-- -->

14. Seja $\Omega$ um conjunto não-enumerável. $\mathbb{S} = \{\{\omega\}: \omega \in \Omega\} \cup \{\phi\}$. Provar que $\mathbb{S}$ é semi-anel. Descrever $\tilde{\sigma}(\mathbb{S})$ e $\sigma(\mathbb{S})$.
15. Consideremos em $\mathbb{R}^2$ as seguintes classes de conjuntos: $\mathscr{C}_1 = \{x \times \mathbb{R}^1: x \in \mathbb{R}^1\}$; $\mathscr{C}_2 = \{\mathbb{R}^1 \times y: y \in \mathbb{R}^1\}$; $\mathscr{B}_1 = \{A \times \mathbb{R}^1: A \text{ boreliano de } \mathbb{R}^1\}$; $\mathscr{B}_2 = \{\mathbb{R}_1 \times A: A \text{ boreliano de } \mathbb{R}^1\}$. Calcular:

<!-- -->

a)  $\mathscr{B}_1 \cap \mathscr{B}_2$;
b)  $\tilde{\sigma}(\mathscr{C}_1), \tilde{\sigma}(\mathscr{C}_2), \sigma(\mathscr{C}_1), \sigma(\mathscr{C}_2)$;
c)  $\sigma(\mathscr{B}_1) \cap \sigma(\mathscr{C}_2)$.
